name: Continuous Integration

on:
  push:
    paths-ignore:
      - '**.md'
      - LICENSE
    branches:
      - "*"
  pull_request:
    paths-ignore:
      - '**.md'
      - LICENSE
    branches:
      - "*"
  workflow_dispatch:

env:
  dotnet-version: 6.0.x

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Set up dotnet environment
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{env.dotnet-version}}
      - name: Set up tools
        run: dotnet tool restore
      - name: Build project
        run: dotnet build .